apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
  namespace: tekton-pipelines
spec:
  params:
    - name: username
      type: string
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Goodbye $(params.username)!"